// Schéma des collections Firestore — porté des migrations SQL Supabase (supprimées).
// Source de vérité des colonnes, valeurs par défaut, clés, unicités et clés étrangères,
// appliqués par la couche d'accès (./query.ts) puisque Firestore n'a pas de schéma.
// Contraintes CHECK et déclencheurs : voir ./constraints.ts.
import type { TableSchema } from './types.js';

export const TABLES = {
  profiles: {
    primaryKey: ['id'],
    columns: {
      id: { type: 'uuid', notNull: true },
      email: { type: 'text', notNull: true },
      role: { type: 'text', notNull: true },
      full_name: { type: 'text', notNull: true },
      phone: { type: 'text' },
      level: { type: 'text' },
      status: { type: 'text', notNull: true, default: { value: 'active' } },
      must_change_password: { type: 'boolean', notNull: true, default: { value: true } },
      created_by: { type: 'uuid' },
      created_at: { type: 'timestamp', notNull: true, default: 'now' },
      updated_at: { type: 'timestamp', notNull: true, default: 'now' },
      email_notifications: { type: 'boolean', notNull: true, default: { value: true } },
      suspended_at: { type: 'timestamp' },
    },
    unique: [
      { columns: ['email'] },
    ],
    foreignKeys: [
      { name: 'profiles_created_by_fkey', columns: ['created_by'], table: 'profiles', references: ['id'], onDelete: 'set null' },
    ],
  },
  programs: {
    primaryKey: ['id'],
    columns: {
      id: { type: 'uuid', notNull: true, default: 'uuid' },
      name: { type: 'text', notNull: true },
      level: { type: 'text' },
      description: { type: 'text' },
      is_active: { type: 'boolean', notNull: true, default: { value: true } },
      created_at: { type: 'timestamp', notNull: true, default: 'now' },
      slug: { type: 'text' },
      is_public: { type: 'boolean', notNull: true, default: { value: false } },
      summary: { type: 'text' },
      duration_label: { type: 'text' },
      schedule_label: { type: 'text' },
      audience: { type: 'text' },
      objectives: { type: 'json', notNull: true, default: { value: [] } },
      display_order: { type: 'integer', notNull: true, default: { value: 0 } },
    },
    unique: [
      { columns: ['slug'] },
    ],
  },
  classes: {
    primaryKey: ['id'],
    columns: {
      id: { type: 'uuid', notNull: true, default: 'uuid' },
      name: { type: 'text', notNull: true },
      program_id: { type: 'uuid' },
      teacher_id: { type: 'uuid' },
      is_active: { type: 'boolean', notNull: true, default: { value: true } },
      created_at: { type: 'timestamp', notNull: true, default: 'now' },
    },
    foreignKeys: [
      { name: 'classes_program_id_fkey', columns: ['program_id'], table: 'programs', references: ['id'], onDelete: 'set null' },
      { name: 'classes_teacher_id_fkey', columns: ['teacher_id'], table: 'profiles', references: ['id'], onDelete: 'set null' },
    ],
  },
  class_students: {
    primaryKey: ['class_id','student_id'],
    columns: {
      class_id: { type: 'uuid', notNull: true },
      student_id: { type: 'uuid', notNull: true },
      added_at: { type: 'timestamp', notNull: true, default: 'now' },
    },
    foreignKeys: [
      { name: 'class_students_class_id_fkey', columns: ['class_id'], table: 'classes', references: ['id'], onDelete: 'cascade' },
      { name: 'class_students_student_id_fkey', columns: ['student_id'], table: 'profiles', references: ['id'], onDelete: 'cascade' },
    ],
  },
  enrollments: {
    primaryKey: ['id'],
    columns: {
      id: { type: 'uuid', notNull: true, default: 'uuid' },
      student_id: { type: 'uuid', notNull: true },
      program_id: { type: 'uuid', notNull: true },
      status: { type: 'text', notNull: true, default: { value: 'active' } },
      enrolled_at: { type: 'timestamp', notNull: true, default: 'now' },
    },
    unique: [
      { columns: ['student_id','program_id'] },
    ],
    foreignKeys: [
      { name: 'enrollments_student_id_fkey', columns: ['student_id'], table: 'profiles', references: ['id'], onDelete: 'cascade' },
      { name: 'enrollments_program_id_fkey', columns: ['program_id'], table: 'programs', references: ['id'], onDelete: 'restrict' },
    ],
  },
  announcements: {
    primaryKey: ['id'],
    columns: {
      id: { type: 'uuid', notNull: true, default: 'uuid' },
      title: { type: 'text', notNull: true },
      body: { type: 'text', notNull: true },
      target: { type: 'text', notNull: true, default: { value: 'all' } },
      target_class_id: { type: 'uuid' },
      published_by: { type: 'uuid' },
      published_at: { type: 'timestamp', notNull: true, default: 'now' },
    },
    foreignKeys: [
      { name: 'announcements_target_class_id_fkey', columns: ['target_class_id'], table: 'classes', references: ['id'], onDelete: 'cascade' },
      { name: 'announcements_published_by_fkey', columns: ['published_by'], table: 'profiles', references: ['id'], onDelete: 'set null' },
    ],
  },
  audit_logs: {
    primaryKey: ['id'],
    columns: {
      id: { type: 'uuid', notNull: true, default: 'uuid' },
      actor_id: { type: 'uuid' },
      action: { type: 'text', notNull: true },
      entity_type: { type: 'text', notNull: true },
      entity_id: { type: 'uuid' },
      metadata: { type: 'json', notNull: true, default: { value: {} } },
      created_at: { type: 'timestamp', notNull: true, default: 'now' },
    },
    foreignKeys: [
      { name: 'audit_logs_actor_id_fkey', columns: ['actor_id'], table: 'profiles', references: ['id'], onDelete: 'set null' },
    ],
  },
  test_templates: {
    primaryKey: ['id'],
    columns: {
      id: { type: 'uuid', notNull: true, default: 'uuid' },
      code: { type: 'text', notNull: true },
      name: { type: 'text', notNull: true },
      language: { type: 'text', notNull: true, default: { value: 'it' } },
      description: { type: 'text' },
      total_duration_seconds: { type: 'integer', notNull: true },
      scoring_rules: { type: 'json', notNull: true, default: { value: { correct: 1, wrong: 0, blank: 0 } } },
      is_active: { type: 'boolean', notNull: true, default: { value: true } },
      version: { type: 'integer', notNull: true, default: { value: 1 } },
      created_by: { type: 'uuid' },
      created_at: { type: 'timestamp', notNull: true, default: 'now' },
      updated_at: { type: 'timestamp', notNull: true, default: 'now' },
    },
    unique: [
      { columns: ['code'] },
    ],
    foreignKeys: [
      { name: 'test_templates_created_by_fkey', columns: ['created_by'], table: 'profiles', references: ['id'], onDelete: 'set null' },
    ],
  },
  test_sections: {
    primaryKey: ['id'],
    columns: {
      id: { type: 'uuid', notNull: true, default: 'uuid' },
      template_id: { type: 'uuid', notNull: true },
      name: { type: 'text', notNull: true },
      category: { type: 'text', notNull: true },
      question_count: { type: 'integer', notNull: true },
      order_index: { type: 'integer', notNull: true },
    },
    unique: [
      { columns: ['template_id','order_index'] },
    ],
    foreignKeys: [
      { name: 'test_sections_template_id_fkey', columns: ['template_id'], table: 'test_templates', references: ['id'], onDelete: 'cascade' },
    ],
  },
  questions: {
    primaryKey: ['id'],
    columns: {
      id: { type: 'uuid', notNull: true, default: 'uuid' },
      category: { type: 'text', notNull: true },
      difficulty: { type: 'integer', notNull: true },
      question_text: { type: 'text', notNull: true },
      options: { type: 'json', notNull: true },
      correct_answer: { type: 'text', notNull: true },
      explanation: { type: 'text' },
      language: { type: 'text', notNull: true, default: { value: 'it' } },
      source: { type: 'text', notNull: true, default: { value: 'manual' } },
      validation_status: { type: 'text', notNull: true, default: { value: 'draft' } },
      validated_by: { type: 'uuid' },
      created_by: { type: 'uuid' },
      version: { type: 'integer', notNull: true, default: { value: 1 } },
      created_at: { type: 'timestamp', notNull: true, default: 'now' },
      updated_at: { type: 'timestamp', notNull: true, default: 'now' },
      generated_from: { type: 'uuid' },
    },
    foreignKeys: [
      { name: 'questions_validated_by_fkey', columns: ['validated_by'], table: 'profiles', references: ['id'], onDelete: 'set null' },
      { name: 'questions_created_by_fkey', columns: ['created_by'], table: 'profiles', references: ['id'], onDelete: 'set null' },
      { name: 'questions_generated_from_fkey', columns: ['generated_from'], table: 'questions', references: ['id'], onDelete: 'set null' },
    ],
  },
  simulations: {
    primaryKey: ['id'],
    columns: {
      id: { type: 'uuid', notNull: true, default: 'uuid' },
      student_id: { type: 'uuid', notNull: true },
      test_template_id: { type: 'uuid' },
      template_version: { type: 'integer' },
      mode: { type: 'text', notNull: true, default: { value: 'examen' } },
      status: { type: 'text', notNull: true, default: { value: 'in_progress' } },
      started_at: { type: 'timestamp', notNull: true, default: 'now' },
      deadline_at: { type: 'timestamp', notNull: true },
      completed_at: { type: 'timestamp' },
      total_questions: { type: 'integer', notNull: true },
      current_position: { type: 'integer', notNull: true, default: { value: 0 } },
      score: { type: 'number' },
      score_by_section: { type: 'json' },
    },
    unique: [
      { columns: ['student_id'], where: (row) => row.status === 'in_progress' },
    ],
    foreignKeys: [
      { name: 'simulations_student_id_fkey', columns: ['student_id'], table: 'profiles', references: ['id'], onDelete: 'cascade' },
      { name: 'simulations_test_template_id_fkey', columns: ['test_template_id'], table: 'test_templates', references: ['id'], onDelete: 'restrict' },
    ],
  },
  simulation_questions: {
    primaryKey: ['simulation_id','position'],
    columns: {
      simulation_id: { type: 'uuid', notNull: true },
      position: { type: 'integer', notNull: true },
      question_id: { type: 'uuid', notNull: true },
      section_id: { type: 'uuid' },
    },
    unique: [
      { columns: ['simulation_id','question_id'] },
    ],
    foreignKeys: [
      { name: 'simulation_questions_simulation_id_fkey', columns: ['simulation_id'], table: 'simulations', references: ['id'], onDelete: 'cascade' },
      { name: 'simulation_questions_question_id_fkey', columns: ['question_id'], table: 'questions', references: ['id'], onDelete: 'restrict' },
      { name: 'simulation_questions_section_id_fkey', columns: ['section_id'], table: 'test_sections', references: ['id'], onDelete: 'set null' },
    ],
  },
  simulation_answers: {
    primaryKey: ['simulation_id','position'],
    columns: {
      simulation_id: { type: 'uuid', notNull: true },
      position: { type: 'integer', notNull: true },
      question_id: { type: 'uuid', notNull: true },
      answer_given: { type: 'text' },
      is_correct: { type: 'boolean', notNull: true },
      time_spent_seconds: { type: 'integer', notNull: true, default: { value: 0 } },
      answered_at: { type: 'timestamp', notNull: true, default: 'now' },
    },
    foreignKeys: [
      { name: 'simulation_answers_simulation_id_fkey', columns: ['simulation_id'], table: 'simulations', references: ['id'], onDelete: 'cascade' },
      { name: 'simulation_answers_question_id_fkey', columns: ['question_id'], table: 'questions', references: ['id'], onDelete: 'restrict' },
      { name: 'simulation_answers_simulation_id_position_fkey', columns: ['simulation_id','position'], table: 'simulation_questions', references: ['simulation_id','position'], onDelete: 'cascade' },
    ],
  },
  embassy_sessions: {
    primaryKey: ['id'],
    columns: {
      id: { type: 'uuid', notNull: true, default: 'uuid' },
      student_id: { type: 'uuid', notNull: true },
      visa_type: { type: 'text', notNull: true },
      scenario_code: { type: 'text', notNull: true, default: { value: 'standard' } },
      input_mode: { type: 'text', notNull: true, default: { value: 'text' } },
      status: { type: 'text', notNull: true, default: { value: 'in_progress' } },
      prompt_version: { type: 'text', notNull: true },
      model: { type: 'text', notNull: true },
      max_turns: { type: 'integer', notNull: true },
      turn_count: { type: 'integer', notNull: true, default: { value: 0 } },
      started_at: { type: 'timestamp', notNull: true, default: 'now' },
      ended_at: { type: 'timestamp' },
      completed_at: { type: 'timestamp' },
      overall_score: { type: 'integer' },
      ai_report: { type: 'json' },
      report_attempts: { type: 'integer', notNull: true, default: { value: 0 } },
      report_claimed_at: { type: 'timestamp' },
      failure_reason: { type: 'text' },
      uses_profile: { type: 'boolean', notNull: true, default: { value: false } },
      profile_snapshot: { type: 'json' },
      cost_limit_reached: { type: 'boolean', notNull: true, default: { value: false } },
    },
    unique: [
      { columns: ['student_id'], where: (row) => row.status === 'in_progress' },
    ],
    foreignKeys: [
      { name: 'embassy_sessions_student_id_fkey', columns: ['student_id'], table: 'profiles', references: ['id'], onDelete: 'cascade' },
      { name: 'embassy_sessions_scenario_fkey', columns: ['scenario_code'], table: 'embassy_scenarios', references: ['code'], onDelete: 'no action' },
    ],
  },
  embassy_messages: {
    primaryKey: ['id'],
    columns: {
      id: { type: 'uuid', notNull: true, default: 'uuid' },
      session_id: { type: 'uuid', notNull: true },
      speaker: { type: 'text', notNull: true },
      sequence_number: { type: 'integer', notNull: true },
      text_content: { type: 'text', notNull: true },
      api_content: { type: 'json' },
      response_time_seconds: { type: 'integer' },
      created_at: { type: 'timestamp', notNull: true, default: 'now' },
    },
    unique: [
      { columns: ['session_id','sequence_number'] },
    ],
    foreignKeys: [
      { name: 'embassy_messages_session_id_fkey', columns: ['session_id'], table: 'embassy_sessions', references: ['id'], onDelete: 'cascade' },
    ],
  },
  ai_usage_logs: {
    primaryKey: ['id'],
    columns: {
      id: { type: 'uuid', notNull: true, default: 'uuid' },
      student_id: { type: 'uuid' },
      session_id: { type: 'uuid' },
      operation: { type: 'text', notNull: true },
      model: { type: 'text', notNull: true },
      input_tokens: { type: 'integer', notNull: true, default: { value: 0 } },
      output_tokens: { type: 'integer', notNull: true, default: { value: 0 } },
      cache_read_input_tokens: { type: 'integer', notNull: true, default: { value: 0 } },
      cache_creation_input_tokens: { type: 'integer', notNull: true, default: { value: 0 } },
      estimated_cost: { type: 'number', notNull: true, default: { value: 0 } },
      created_at: { type: 'timestamp', notNull: true, default: 'now' },
    },
    foreignKeys: [
      { name: 'ai_usage_logs_student_id_fkey', columns: ['student_id'], table: 'profiles', references: ['id'], onDelete: 'set null' },
    ],
  },
  courses: {
    primaryKey: ['id'],
    columns: {
      id: { type: 'uuid', notNull: true, default: 'uuid' },
      title: { type: 'text', notNull: true },
      description: { type: 'text' },
      level: { type: 'text', notNull: true },
      category: { type: 'text', notNull: true },
      content_type: { type: 'text', notNull: true },
      body: { type: 'text' },
      content_url: { type: 'text' },
      class_id: { type: 'uuid' },
      is_published: { type: 'boolean', notNull: true, default: { value: false } },
      published_at: { type: 'timestamp' },
      created_by: { type: 'uuid' },
      created_at: { type: 'timestamp', notNull: true, default: 'now' },
      updated_at: { type: 'timestamp', notNull: true, default: 'now' },
    },
    foreignKeys: [
      { name: 'courses_class_id_fkey', columns: ['class_id'], table: 'classes', references: ['id'], onDelete: 'set null' },
      { name: 'courses_created_by_fkey', columns: ['created_by'], table: 'profiles', references: ['id'], onDelete: 'set null' },
    ],
  },
  exercises: {
    primaryKey: ['id'],
    columns: {
      id: { type: 'uuid', notNull: true, default: 'uuid' },
      course_id: { type: 'uuid' },
      title: { type: 'text', notNull: true },
      level: { type: 'text', notNull: true },
      category: { type: 'text', notNull: true },
      exercise_type: { type: 'text', notNull: true },
      instructions: { type: 'text' },
      content: { type: 'json', notNull: true },
      solution: { type: 'json', notNull: true },
      is_published: { type: 'boolean', notNull: true, default: { value: false } },
      created_by: { type: 'uuid' },
      created_at: { type: 'timestamp', notNull: true, default: 'now' },
      updated_at: { type: 'timestamp', notNull: true, default: 'now' },
    },
    foreignKeys: [
      { name: 'exercises_course_id_fkey', columns: ['course_id'], table: 'courses', references: ['id'], onDelete: 'set null' },
      { name: 'exercises_created_by_fkey', columns: ['created_by'], table: 'profiles', references: ['id'], onDelete: 'set null' },
    ],
  },
  exercise_attempts: {
    primaryKey: ['id'],
    columns: {
      id: { type: 'uuid', notNull: true, default: 'uuid' },
      exercise_id: { type: 'uuid', notNull: true },
      student_id: { type: 'uuid', notNull: true },
      answers: { type: 'json', notNull: true },
      score: { type: 'integer', notNull: true },
      max_score: { type: 'integer', notNull: true },
      created_at: { type: 'timestamp', notNull: true, default: 'now' },
    },
    foreignKeys: [
      { name: 'exercise_attempts_exercise_id_fkey', columns: ['exercise_id'], table: 'exercises', references: ['id'], onDelete: 'cascade' },
      { name: 'exercise_attempts_student_id_fkey', columns: ['student_id'], table: 'profiles', references: ['id'], onDelete: 'cascade' },
    ],
  },
  level_test_questions: {
    primaryKey: ['id'],
    columns: {
      id: { type: 'uuid', notNull: true, default: 'uuid' },
      level: { type: 'text', notNull: true },
      question_text: { type: 'text', notNull: true },
      options: { type: 'json', notNull: true },
      correct_answer: { type: 'text', notNull: true },
      order_index: { type: 'integer', notNull: true },
      is_active: { type: 'boolean', notNull: true, default: { value: true } },
    },
    unique: [
      { columns: ['order_index'] },
    ],
  },
  level_test_attempts: {
    primaryKey: ['id'],
    columns: {
      id: { type: 'uuid', notNull: true, default: 'uuid' },
      answers: { type: 'json', notNull: true },
      score: { type: 'integer', notNull: true },
      total: { type: 'integer', notNull: true },
      estimated_level: { type: 'text' },
      full_name: { type: 'text' },
      email: { type: 'text' },
      phone: { type: 'text' },
      desired_program: { type: 'text' },
      contact_consent: { type: 'boolean', notNull: true, default: { value: false } },
      created_at: { type: 'timestamp', notNull: true, default: 'now' },
    },
  },
  class_sessions: {
    primaryKey: ['id'],
    columns: {
      id: { type: 'uuid', notNull: true, default: 'uuid' },
      class_id: { type: 'uuid', notNull: true },
      title: { type: 'text', notNull: true },
      starts_at: { type: 'timestamp', notNull: true },
      ends_at: { type: 'timestamp', notNull: true },
      location: { type: 'text' },
      notes: { type: 'text' },
      created_by: { type: 'uuid' },
      created_at: { type: 'timestamp', notNull: true, default: 'now' },
    },
    foreignKeys: [
      { name: 'class_sessions_class_id_fkey', columns: ['class_id'], table: 'classes', references: ['id'], onDelete: 'cascade' },
      { name: 'class_sessions_created_by_fkey', columns: ['created_by'], table: 'profiles', references: ['id'], onDelete: 'set null' },
    ],
  },
  site_settings: {
    primaryKey: ['id'],
    columns: {
      id: { type: 'boolean', notNull: true, default: { value: true } },
      centre_name: { type: 'text', notNull: true, default: { value: 'Salve Italia' } },
      tagline: { type: 'text' },
      about: { type: 'text' },
      phone: { type: 'text' },
      whatsapp: { type: 'text' },
      email: { type: 'text' },
      address: { type: 'text' },
      opening_hours: { type: 'text' },
      facebook_url: { type: 'text' },
      instagram_url: { type: 'text' },
      map_url: { type: 'text' },
      key_figures: { type: 'json', notNull: true, default: { value: [] } },
      updated_by: { type: 'uuid' },
      updated_at: { type: 'timestamp', notNull: true, default: 'now' },
    },
    foreignKeys: [
      { name: 'site_settings_updated_by_fkey', columns: ['updated_by'], table: 'profiles', references: ['id'], onDelete: 'set null' },
    ],
  },
  testimonials: {
    primaryKey: ['id'],
    columns: {
      id: { type: 'uuid', notNull: true, default: 'uuid' },
      author_name: { type: 'text', notNull: true },
      author_context: { type: 'text' },
      quote: { type: 'text', notNull: true },
      photo_url: { type: 'text' },
      consent_confirmed: { type: 'boolean', notNull: true, default: { value: false } },
      is_published: { type: 'boolean', notNull: true, default: { value: false } },
      display_order: { type: 'integer', notNull: true, default: { value: 0 } },
      created_at: { type: 'timestamp', notNull: true, default: 'now' },
    },
  },
  faq_items: {
    primaryKey: ['id'],
    columns: {
      id: { type: 'uuid', notNull: true, default: 'uuid' },
      question: { type: 'text', notNull: true },
      answer: { type: 'text', notNull: true },
      is_published: { type: 'boolean', notNull: true, default: { value: true } },
      display_order: { type: 'integer', notNull: true, default: { value: 0 } },
      created_at: { type: 'timestamp', notNull: true, default: 'now' },
    },
  },
  gallery_images: {
    primaryKey: ['id'],
    columns: {
      id: { type: 'uuid', notNull: true, default: 'uuid' },
      image_url: { type: 'text', notNull: true },
      alt_text: { type: 'text', notNull: true },
      caption: { type: 'text' },
      is_published: { type: 'boolean', notNull: true, default: { value: false } },
      display_order: { type: 'integer', notNull: true, default: { value: 0 } },
      created_at: { type: 'timestamp', notNull: true, default: 'now' },
    },
  },
  leads: {
    primaryKey: ['id'],
    columns: {
      id: { type: 'uuid', notNull: true, default: 'uuid' },
      full_name: { type: 'text', notNull: true },
      phone: { type: 'text' },
      email: { type: 'text' },
      desired_program: { type: 'text' },
      level_estimate: { type: 'text' },
      message: { type: 'text' },
      source: { type: 'text', notNull: true },
      status: { type: 'text', notNull: true, default: { value: 'nouveau' } },
      notes: { type: 'text' },
      next_follow_up_at: { type: 'timestamp' },
      assigned_to: { type: 'uuid' },
      contact_consent: { type: 'boolean', notNull: true },
      created_at: { type: 'timestamp', notNull: true, default: 'now' },
      updated_at: { type: 'timestamp', notNull: true, default: 'now' },
    },
    foreignKeys: [
      { name: 'leads_assigned_to_fkey', columns: ['assigned_to'], table: 'profiles', references: ['id'], onDelete: 'set null' },
    ],
  },
  student_profiles: {
    primaryKey: ['student_id'],
    columns: {
      student_id: { type: 'uuid', notNull: true },
      current_education_level: { type: 'text' },
      diplomas: { type: 'json', notNull: true, default: { value: [] } },
      english_level: { type: 'text' },
      desired_field: { type: 'text' },
      preferred_cities: { type: 'json', notNull: true, default: { value: [] } },
      institution_type_preference: { type: 'text' },
      study_objective: { type: 'text' },
      budget_range: { type: 'text' },
      financing_source: { type: 'text' },
      project_stage: { type: 'text' },
      target_intake: { type: 'text' },
      target_template_id: { type: 'uuid' },
      updated_at: { type: 'timestamp', notNull: true, default: 'now' },
      visa_type: { type: 'text' },
      has_guarantor: { type: 'boolean' },
    },
    foreignKeys: [
      { name: 'student_profiles_student_id_fkey', columns: ['student_id'], table: 'profiles', references: ['id'], onDelete: 'cascade' },
      { name: 'student_profiles_target_template_id_fkey', columns: ['target_template_id'], table: 'test_templates', references: ['id'], onDelete: 'set null' },
    ],
  },
  student_question_stats: {
    primaryKey: ['student_id','question_id'],
    columns: {
      student_id: { type: 'uuid', notNull: true },
      question_id: { type: 'uuid', notNull: true },
      attempts_count: { type: 'integer', notNull: true, default: { value: 0 } },
      correct_count: { type: 'integer', notNull: true, default: { value: 0 } },
      mastery_score: { type: 'number', notNull: true, default: { value: 0 } },
      interval_days: { type: 'integer', notNull: true, default: { value: 0 } },
      last_correct: { type: 'boolean' },
      last_answered_at: { type: 'timestamp' },
      next_review_at: { type: 'timestamp', notNull: true, default: 'now' },
    },
    foreignKeys: [
      { name: 'student_question_stats_student_id_fkey', columns: ['student_id'], table: 'profiles', references: ['id'], onDelete: 'cascade' },
      { name: 'student_question_stats_question_id_fkey', columns: ['question_id'], table: 'questions', references: ['id'], onDelete: 'cascade' },
    ],
  },
  learning_paths: {
    primaryKey: ['student_id'],
    columns: {
      student_id: { type: 'uuid', notNull: true },
      objective: { type: 'text' },
      target_template_id: { type: 'uuid' },
      weekly_goals: { type: 'json', notNull: true, default: { value: [] } },
      recommended_actions: { type: 'json', notNull: true, default: { value: [] } },
      progress_percent: { type: 'integer', notNull: true, default: { value: 0 } },
      generated_at: { type: 'timestamp', notNull: true, default: 'now' },
    },
    foreignKeys: [
      { name: 'learning_paths_student_id_fkey', columns: ['student_id'], table: 'profiles', references: ['id'], onDelete: 'cascade' },
      { name: 'learning_paths_target_template_id_fkey', columns: ['target_template_id'], table: 'test_templates', references: ['id'], onDelete: 'set null' },
    ],
  },
  teacher_feedback: {
    primaryKey: ['id'],
    columns: {
      id: { type: 'uuid', notNull: true, default: 'uuid' },
      student_id: { type: 'uuid', notNull: true },
      target_type: { type: 'text', notNull: true },
      target_id: { type: 'uuid', notNull: true },
      teacher_id: { type: 'uuid' },
      comment: { type: 'text', notNull: true },
      follow_up_at: { type: 'date' },
      status: { type: 'text', notNull: true, default: { value: 'a_revoir' } },
      created_at: { type: 'timestamp', notNull: true, default: 'now' },
      updated_at: { type: 'timestamp', notNull: true, default: 'now' },
    },
    foreignKeys: [
      { name: 'teacher_feedback_student_id_fkey', columns: ['student_id'], table: 'profiles', references: ['id'], onDelete: 'cascade' },
      { name: 'teacher_feedback_teacher_id_fkey', columns: ['teacher_id'], table: 'profiles', references: ['id'], onDelete: 'set null' },
    ],
  },
  document_types: {
    primaryKey: ['code'],
    columns: {
      code: { type: 'text', notNull: true },
      label: { type: 'text', notNull: true },
      description: { type: 'text' },
      requires_expiry: { type: 'boolean', notNull: true, default: { value: false } },
      display_order: { type: 'integer', notNull: true, default: { value: 0 } },
      is_active: { type: 'boolean', notNull: true, default: { value: true } },
    },
  },
  checklist_requirements: {
    primaryKey: ['id'],
    columns: {
      id: { type: 'uuid', notNull: true, default: 'uuid' },
      code: { type: 'text', notNull: true },
      label: { type: 'text', notNull: true },
      description: { type: 'text' },
      document_type: { type: 'text' },
      visa_types: { type: 'array', notNull: true, default: { value: ['etudes', 'tourisme', 'travail'] } },
      financing_sources: { type: 'array' },
      requires_guarantor: { type: 'boolean' },
      source_label: { type: 'text' },
      source_url: { type: 'text' },
      last_verified_at: { type: 'date' },
      requires_human_verification: { type: 'boolean', notNull: true, default: { value: true } },
      display_order: { type: 'integer', notNull: true, default: { value: 0 } },
      is_active: { type: 'boolean', notNull: true, default: { value: true } },
      updated_by: { type: 'uuid' },
      updated_at: { type: 'timestamp', notNull: true, default: 'now' },
    },
    unique: [
      { columns: ['code'] },
    ],
    foreignKeys: [
      { name: 'checklist_requirements_document_type_fkey', columns: ['document_type'], table: 'document_types', references: ['code'], onDelete: 'set null' },
      { name: 'checklist_requirements_updated_by_fkey', columns: ['updated_by'], table: 'profiles', references: ['id'], onDelete: 'set null' },
    ],
  },
  student_documents: {
    primaryKey: ['id'],
    columns: {
      id: { type: 'uuid', notNull: true, default: 'uuid' },
      student_id: { type: 'uuid', notNull: true },
      document_type: { type: 'text', notNull: true },
      status: { type: 'text', notNull: true, default: { value: 'submitted' } },
      current_version: { type: 'integer', notNull: true, default: { value: 1 } },
      storage_path: { type: 'text', notNull: true },
      file_name: { type: 'text', notNull: true },
      mime_type: { type: 'text', notNull: true },
      size_bytes: { type: 'integer', notNull: true },
      expires_at: { type: 'date' },
      reviewer_comment: { type: 'text' },
      reviewed_by: { type: 'uuid' },
      reviewed_at: { type: 'timestamp' },
      expiry_notified_at: { type: 'timestamp' },
      created_at: { type: 'timestamp', notNull: true, default: 'now' },
      updated_at: { type: 'timestamp', notNull: true, default: 'now' },
    },
    unique: [
      { columns: ['student_id','document_type'] },
    ],
    foreignKeys: [
      { name: 'student_documents_student_id_fkey', columns: ['student_id'], table: 'profiles', references: ['id'], onDelete: 'cascade' },
      { name: 'student_documents_document_type_fkey', columns: ['document_type'], table: 'document_types', references: ['code'], onDelete: 'restrict' },
      { name: 'student_documents_reviewed_by_fkey', columns: ['reviewed_by'], table: 'profiles', references: ['id'], onDelete: 'set null' },
    ],
  },
  student_document_versions: {
    primaryKey: ['id'],
    columns: {
      id: { type: 'uuid', notNull: true, default: 'uuid' },
      document_id: { type: 'uuid', notNull: true },
      version: { type: 'integer', notNull: true },
      storage_path: { type: 'text', notNull: true },
      file_name: { type: 'text', notNull: true },
      mime_type: { type: 'text', notNull: true },
      size_bytes: { type: 'integer', notNull: true },
      uploaded_by: { type: 'uuid' },
      uploaded_at: { type: 'timestamp', notNull: true, default: 'now' },
    },
    unique: [
      { columns: ['storage_path'] },
      { columns: ['document_id','version'] },
    ],
    foreignKeys: [
      { name: 'student_document_versions_document_id_fkey', columns: ['document_id'], table: 'student_documents', references: ['id'], onDelete: 'cascade' },
      { name: 'student_document_versions_uploaded_by_fkey', columns: ['uploaded_by'], table: 'profiles', references: ['id'], onDelete: 'set null' },
    ],
  },
  document_events: {
    primaryKey: ['id'],
    columns: {
      id: { type: 'uuid', notNull: true, default: 'uuid' },
      document_id: { type: 'uuid', notNull: true },
      actor_id: { type: 'uuid' },
      action: { type: 'text', notNull: true },
      version: { type: 'integer' },
      comment: { type: 'text' },
      created_at: { type: 'timestamp', notNull: true, default: 'now' },
    },
    foreignKeys: [
      { name: 'document_events_document_id_fkey', columns: ['document_id'], table: 'student_documents', references: ['id'], onDelete: 'cascade' },
      { name: 'document_events_actor_id_fkey', columns: ['actor_id'], table: 'profiles', references: ['id'], onDelete: 'set null' },
    ],
  },
  notifications: {
    primaryKey: ['id'],
    columns: {
      id: { type: 'uuid', notNull: true, default: 'uuid' },
      user_id: { type: 'uuid', notNull: true },
      type: { type: 'text', notNull: true },
      title: { type: 'text', notNull: true },
      body: { type: 'text' },
      link: { type: 'text' },
      dedupe_key: { type: 'text' },
      read_at: { type: 'timestamp' },
      created_at: { type: 'timestamp', notNull: true, default: 'now' },
    },
    unique: [
      { columns: ['user_id','dedupe_key'] },
    ],
    foreignKeys: [
      { name: 'notifications_user_id_fkey', columns: ['user_id'], table: 'profiles', references: ['id'], onDelete: 'cascade' },
    ],
  },
  email_outbox: {
    primaryKey: ['id'],
    columns: {
      id: { type: 'uuid', notNull: true, default: 'uuid' },
      notification_id: { type: 'uuid' },
      to_email: { type: 'text', notNull: true },
      subject: { type: 'text', notNull: true },
      body_text: { type: 'text', notNull: true },
      status: { type: 'text', notNull: true, default: { value: 'pending' } },
      attempts: { type: 'integer', notNull: true, default: { value: 0 } },
      last_error: { type: 'text' },
      next_attempt_at: { type: 'timestamp', notNull: true, default: 'now' },
      sent_at: { type: 'timestamp' },
      created_at: { type: 'timestamp', notNull: true, default: 'now' },
    },
    foreignKeys: [
      { name: 'email_outbox_notification_id_fkey', columns: ['notification_id'], table: 'notifications', references: ['id'], onDelete: 'cascade' },
    ],
  },
  lead_interactions: {
    primaryKey: ['id'],
    columns: {
      id: { type: 'uuid', notNull: true, default: 'uuid' },
      lead_id: { type: 'uuid', notNull: true },
      actor_id: { type: 'uuid' },
      kind: { type: 'text', notNull: true },
      summary: { type: 'text', notNull: true },
      created_at: { type: 'timestamp', notNull: true, default: 'now' },
    },
    foreignKeys: [
      { name: 'lead_interactions_lead_id_fkey', columns: ['lead_id'], table: 'leads', references: ['id'], onDelete: 'cascade' },
      { name: 'lead_interactions_actor_id_fkey', columns: ['actor_id'], table: 'profiles', references: ['id'], onDelete: 'set null' },
    ],
  },
  embassy_scenarios: {
    primaryKey: ['code'],
    columns: {
      code: { type: 'text', notNull: true },
      label: { type: 'text', notNull: true },
      description: { type: 'text', notNull: true },
      visa_types: { type: 'array', notNull: true, default: { value: ['etudes', 'tourisme', 'travail'] } },
      agent_instructions: { type: 'text', notNull: true },
      focus_themes: { type: 'array', notNull: true, default: { value: [] } },
      is_active: { type: 'boolean', notNull: true, default: { value: true } },
      display_order: { type: 'integer', notNull: true, default: { value: 0 } },
      updated_by: { type: 'uuid' },
      updated_at: { type: 'timestamp', notNull: true, default: 'now' },
    },
    foreignKeys: [
      { name: 'embassy_scenarios_updated_by_fkey', columns: ['updated_by'], table: 'profiles', references: ['id'], onDelete: 'set null' },
    ],
  },
  ai_settings: {
    primaryKey: ['id'],
    columns: {
      id: { type: 'boolean', notNull: true, default: { value: true } },
      max_turns: { type: 'integer' },
      weekly_session_limit: { type: 'integer' },
      monthly_cost_limit_usd: { type: 'number' },
      session_cost_limit_usd: { type: 'number' },
      updated_by: { type: 'uuid' },
      updated_at: { type: 'timestamp', notNull: true, default: 'now' },
    },
    foreignKeys: [
      { name: 'ai_settings_updated_by_fkey', columns: ['updated_by'], table: 'profiles', references: ['id'], onDelete: 'set null' },
    ],
  },
  student_ai_limits: {
    primaryKey: ['student_id'],
    columns: {
      student_id: { type: 'uuid', notNull: true },
      weekly_session_limit: { type: 'integer' },
      monthly_cost_limit_usd: { type: 'number' },
      note: { type: 'text' },
      updated_by: { type: 'uuid' },
      updated_at: { type: 'timestamp', notNull: true, default: 'now' },
    },
    foreignKeys: [
      { name: 'student_ai_limits_student_id_fkey', columns: ['student_id'], table: 'profiles', references: ['id'], onDelete: 'cascade' },
      { name: 'student_ai_limits_updated_by_fkey', columns: ['updated_by'], table: 'profiles', references: ['id'], onDelete: 'set null' },
    ],
  },
  retention_settings: {
    primaryKey: ['id'],
    columns: {
      id: { type: 'boolean', notNull: true, default: { value: true } },
      embassy_sessions_months: { type: 'integer' },
      suspended_students_months: { type: 'integer' },
      document_versions_months: { type: 'integer' },
      leads_months: { type: 'integer' },
      notifications_months: { type: 'integer' },
      updated_by: { type: 'uuid' },
      updated_at: { type: 'timestamp', notNull: true, default: 'now' },
      last_run_at: { type: 'timestamp' },
      last_run_result: { type: 'json' },
    },
    foreignKeys: [
      { name: 'retention_settings_updated_by_fkey', columns: ['updated_by'], table: 'profiles', references: ['id'], onDelete: 'set null' },
    ],
  },
  class_attendance: {
    primaryKey: ['session_id','student_id'],
    columns: {
      session_id: { type: 'uuid', notNull: true },
      student_id: { type: 'uuid', notNull: true },
      status: { type: 'text', notNull: true },
      note: { type: 'text' },
      recorded_by: { type: 'uuid' },
      recorded_at: { type: 'timestamp', notNull: true, default: 'now' },
    },
    foreignKeys: [
      { name: 'class_attendance_session_id_fkey', columns: ['session_id'], table: 'class_sessions', references: ['id'], onDelete: 'cascade' },
      { name: 'class_attendance_student_id_fkey', columns: ['student_id'], table: 'profiles', references: ['id'], onDelete: 'cascade' },
      { name: 'class_attendance_recorded_by_fkey', columns: ['recorded_by'], table: 'profiles', references: ['id'], onDelete: 'set null' },
    ],
  },
  homework_assignments: {
    primaryKey: ['id'],
    columns: {
      id: { type: 'uuid', notNull: true, default: 'uuid' },
      class_id: { type: 'uuid', notNull: true },
      title: { type: 'text', notNull: true },
      instructions: { type: 'text' },
      due_at: { type: 'timestamp', notNull: true },
      course_id: { type: 'uuid' },
      exercise_id: { type: 'uuid' },
      created_by: { type: 'uuid' },
      created_at: { type: 'timestamp', notNull: true, default: 'now' },
      updated_at: { type: 'timestamp', notNull: true, default: 'now' },
    },
    foreignKeys: [
      { name: 'homework_assignments_class_id_fkey', columns: ['class_id'], table: 'classes', references: ['id'], onDelete: 'cascade' },
      { name: 'homework_assignments_course_id_fkey', columns: ['course_id'], table: 'courses', references: ['id'], onDelete: 'set null' },
      { name: 'homework_assignments_exercise_id_fkey', columns: ['exercise_id'], table: 'exercises', references: ['id'], onDelete: 'set null' },
      { name: 'homework_assignments_created_by_fkey', columns: ['created_by'], table: 'profiles', references: ['id'], onDelete: 'set null' },
    ],
  },
  homework_submissions: {
    primaryKey: ['assignment_id','student_id'],
    columns: {
      assignment_id: { type: 'uuid', notNull: true },
      student_id: { type: 'uuid', notNull: true },
      status: { type: 'text', notNull: true, default: { value: 'rendu' } },
      answer: { type: 'text' },
      submitted_at: { type: 'timestamp', notNull: true, default: 'now' },
      teacher_comment: { type: 'text' },
      reviewed_by: { type: 'uuid' },
      reviewed_at: { type: 'timestamp' },
    },
    foreignKeys: [
      { name: 'homework_submissions_assignment_id_fkey', columns: ['assignment_id'], table: 'homework_assignments', references: ['id'], onDelete: 'cascade' },
      { name: 'homework_submissions_student_id_fkey', columns: ['student_id'], table: 'profiles', references: ['id'], onDelete: 'cascade' },
      { name: 'homework_submissions_reviewed_by_fkey', columns: ['reviewed_by'], table: 'profiles', references: ['id'], onDelete: 'set null' },
    ],
  },
  badges: {
    primaryKey: ['id'],
    columns: {
      id: { type: 'uuid', notNull: true, default: 'uuid' },
      code: { type: 'text', notNull: true },
      label: { type: 'text', notNull: true },
      description: { type: 'text', notNull: true },
      sort_order: { type: 'integer', notNull: true, default: { value: 0 } },
      is_active: { type: 'boolean', notNull: true, default: { value: true } },
    },
    unique: [
      { columns: ['code'] },
    ],
  },
  student_badges: {
    primaryKey: ['student_id','badge_id'],
    columns: {
      student_id: { type: 'uuid', notNull: true },
      badge_id: { type: 'uuid', notNull: true },
      awarded_at: { type: 'timestamp', notNull: true, default: 'now' },
    },
    foreignKeys: [
      { name: 'student_badges_student_id_fkey', columns: ['student_id'], table: 'profiles', references: ['id'], onDelete: 'cascade' },
      { name: 'student_badges_badge_id_fkey', columns: ['badge_id'], table: 'badges', references: ['id'], onDelete: 'cascade' },
    ],
  },
  session_settings: {
    primaryKey: ['id'],
    columns: {
      id: { type: 'boolean', notNull: true, default: { value: true } },
      idle_timeout_minutes: { type: 'integer' },
      updated_by: { type: 'uuid' },
      updated_at: { type: 'timestamp', notNull: true, default: 'now' },
    },
    foreignKeys: [
      { name: 'session_settings_updated_by_fkey', columns: ['updated_by'], table: 'profiles', references: ['id'], onDelete: 'set null' },
    ],
  },
} satisfies Record<string, TableSchema>;
